# Generated by Django 2.2.4 on 2019-08-25 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='C2BPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionType', models.CharField(max_length=20)),
                ('TransID', models.CharField(max_length=20)),
                ('TransTime', models.DateTimeField(default=datetime.datetime(2019, 8, 25, 20, 30, 54, 74263))),
                ('TransAmount', models.IntegerField()),
                ('BusinessShortCode', models.IntegerField()),
                ('BillRefNumber', models.IntegerField()),
                ('InvoiceNumber', models.IntegerField()),
                ('OrgAccountBalance', models.IntegerField()),
                ('ThirdPartyTransID', models.CharField(blank=True, default=None, max_length=20)),
                ('MSISDN', models.IntegerField()),
                ('FirstName', models.CharField(max_length=20)),
                ('MiddleName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Validation',
        ),
    ]
