# Generated by Django 2.2.4 on 2019-08-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20190825_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c2bpayment',
            name='BillRefNumber',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='c2bpayment',
            name='BusinessShortCode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='c2bpayment',
            name='InvoiceNumber',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='c2bpayment',
            name='MSISDN',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='c2bpayment',
            name='OrgAccountBalance',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='c2bpayment',
            name='ThirdPartyTransID',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='c2bpayment',
            name='TransAmount',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='c2bpayment',
            name='TransID',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='c2bpayment',
            name='TransTime',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='c2bpayment',
            name='TransactionType',
            field=models.CharField(max_length=50),
        ),
    ]
